version: '3.8'

services:
  crawl4ai:
    image: unclecode/crawl4ai:all-amd64
    platform: linux/amd64
    container_name: crawl4ai-server
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=home
      - MAX_CONCURRENT_TASKS=10
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped