version: '3'
services:
  # 소스 데이터베이스 (PostgreSQL)
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kjy
      POSTGRES_PASSWORD: home
      POSTGRES_DB: source_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-postgres:/docker-entrypoint-initdb.d

  # 타겟 데이터베이스 (MySQL)
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: target_db
      MYSQL_USER: kjy
      MYSQL_PASSWORD: home
    ports:
      - "13306:3306"
    volumes:
      - ./init-mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  # Spark 마스터 노드
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # UI
      - "7077:7077"  # Spark 마스터 포트
    volumes:
      - ./spark-scripts:/opt/spark-scripts

  # Spark 워커 노드
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    volumes:
      - ./spark-scripts:/opt/spark-scripts

  # KRaft 모드의 Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      # KRaft 모드 활성화
      KAFKA_METADATA_LOG_DIR: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'  # 클러스터 ID (임의의 값)

volumes:
  mysql_data: