global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crawler'
    static_configs:
      - targets: ['host.docker.internal:8000']  # 크롤러 메트릭 엔드포인트

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']