# application-dev.yml (개발 환경)
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/source_db
    username: kjy
    password: home

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: homesweethome

crawler:
  crawl4ai-url: http://localhost:11235
  interval-hours: 1  # 개발환경에서는 더 자주 실행

logging:
  level:
    org.be.crawlerservice: DEBUG
    root: INFO

---