# application.yml - ?? ??
server:
  port: 8080

spring:
  application:
    name: crawler-service

  # ?????? ??
  datasource:
    url: jdbc:postgresql://localhost:5432/articles
    username: kjy
    password: home
    driver-class-name: org.postgresql.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  # Redis ??
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # Jackson ??
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

# ?? ????? ??
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# ??? ??
crawler:
  crawl4ai-url: http://localhost:11235
  api-token: home
  interval-hours: 3
  batch-size: 10
  max-concurrent-tasks: 5
  timeout-seconds: 180

# ?? ??
logging:
  level:
    org.be.crawlerservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
