# application.yml - ?? ??
server:
  port: 8080

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  application:
    name: crawler-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_IP}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password: homesweethome
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Seoul

# ?? ????? ??
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# ??? ??
crawler:
  crawl4ai-url: http://localhost:11235
  api-token: home
  interval-hours: 3
  batch-size: 10
  max-concurrent-tasks: 5
  timeout-seconds: 180

# ?? ??
logging:
  level:
    org.be.crawlerservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
