# kafka-2_0_0.yml 설정 파일 생성
  @"
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
    name: kafka_$1_$2_$3
  - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value
    name: kafka_$1_$2_$3
    labels:
      "$4": "$5"
    "@ | Out-File -FilePath .\kafka-2_0_0.yml -Encoding utf8