version: '3'

services:
  crawler:
    image: gcr.io/${GCP_PROJECT_ID}/crawler:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
      - "${METRICS_PORT}:${METRICS_PORT}"
    environment:
      - REDIS_HOST=redis.internal
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - KAFKA_BOOTSTRAP_SERVERS=kafka.internal:9092
      - ENVIRONMENT=production
    volumes:
      - crawler_data:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    depends_on:
      redis:
        condition: service_healthy
    networks:
      infra-network:
        aliases:
          - crawler.internal
    restart: always
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 1gb --maxmemory-policy allkeys-lru
    networks:
      infra-network:
        aliases:
          - redis.internal
    restart: always
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-exporter:
    image: oliver006/redis_exporter:latest
    expose:
      - "9121"
    environment:
      - REDIS_ADDR=redis://redis.internal:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_EXPORTER_LOG_FORMAT=json
    networks:
      infra-network:
        aliases:
          - redis-exporter.internal
    depends_on:
      - redis
    restart: always
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  redis_data:
  crawler_data:

networks:
  infra-network:
    name: infra-network
    driver: bridge