version: '3'
services:
  # 크롤링 서버
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # FastAPI
      - "8000:8000"  # Prometheus metrics
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - redis
    networks:
      - crawler-network
      - crawler-infra

  # Redis (크롤러 전용 캐시)
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - crawler-network

  # Redis Exporter (Redis 메트릭 수집용)
  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - crawler-network
      - crawler-infra

volumes:
  redis_data:

networks:
  crawler-network:
    driver: bridge
  crawler-infra:
    external: true
    name: crawler-infra-network