global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  # 크롤러 메트릭
  - job_name: 'crawler'
    static_configs:
      - targets: ['crawler.internal:8000']

  # Redis 메트릭 (기존 것 유지)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Kafka JMX Exporter
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: [ 'kafka:9999' ]
        labels:
          instance: 'kafka-1'

  # Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          instance: 'kafka-cluster-1'