global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # 크롤러 메트릭
  - job_name: 'crawler'
    static_configs:
      - targets: ['34.64.63.202:9090']

  # Redis 메트릭
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']